export enum Permission {
  ADMIN = "ADMIN",
  CADASTRO_CLIENTE = "CADASTRO_CLIENTE",
  CADASTRO_PRODUTO = "CADASTRO_PRODUTO",
  EFETUAR_VENDA = "EFETUAR_VENDA",
  GERAR_ORDEM_SERVICO = "GERAR_ORDEM_SERVICO",
  MANIPULAR_ESTOQUE = "MANIPULAR_ESTOQUE",
  GERENCIAR_LANDING_PAGE = "GERENCIAR_LANDING_PAGE",
  CRIAR_PERFIL_USUARIO = "CRIAR_PERFIL_USUARIO",
  CRIAR_USUARIO = "CRIAR_USUARIO",
}
